### ISSUE TITLE
create statistics

### ISSUE THREAD

**Issue by nichtich** [gbv/kos-registry#2]
A venn diagram and/or statistics of sources would be nice (how many schemes are described by which sources).

**Comment by nichtich** [comment]
~~~
jq -c '[.uri,.identifier[]?]|length' all.ndjson | sort | uniq -c
     91 1
     37 2
      2 3
      2 4
      1 5
~~~

**Comment by stefandesu** [comment]
The number of identifiers does not represent the number of sources in any way though. This would have to be done by parsing the .ndjson files.
